"""Enterprise Pydantic models for identity, secrets, and tenant management."""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field


class AuthenticatedUser(BaseModel):
    """User identity resolved from a token or SAML assertion."""

    id: str
    email: str
    tenant_id: str
    roles: list[str] = Field(default_factory=list)
    permissions: list[str] = Field(default_factory=list)
    mfa_verified: bool = False
    session_id: str = ""


class SecretMetadata(BaseModel):
    """Metadata for a secret stored in the secrets backend."""

    path: str
    version: int
    created_at: datetime
    expires_at: datetime | None = None
    rotation_policy: str | None = None


class CertificateBundle(BaseModel):
    """TLS certificate bundle issued by a PKI backend."""

    cert: str
    private_key: str
    ca_chain: list[str] = Field(default_factory=list)
    serial: str = ""
    expires_at: datetime | None = None


class DynamicCredential(BaseModel):
    """Short-lived credential generated by a secrets engine."""

    username: str
    password: str
    lease_id: str
    lease_duration: int
    renewable: bool = False


class TenantContext(BaseModel):
    """Runtime context for a resolved tenant."""

    tenant_id: str
    name: str
    vault_namespace: str = ""
    keycloak_realm: str = ""
    features: list[str] = Field(default_factory=list)
    billing_plan: str = "free"


class UserProfile(BaseModel):
    """Full user profile returned by the identity provider."""

    id: str
    email: str
    display_name: str = ""
    groups: list[str] = Field(default_factory=list)
    roles: list[str] = Field(default_factory=list)
    mfa_enabled: bool = False
    scim_external_id: str | None = None


class GroupProfile(BaseModel):
    """Group profile managed via SCIM or identity provider."""

    id: str
    name: str
    members: list[str] = Field(default_factory=list)
    scim_external_id: str | None = None


class SAMLRequest(BaseModel):
    """SAML authentication request redirect data."""

    redirect_url: str
    request_id: str
    relay_state: str = ""


class MFASetupResponse(BaseModel):
    """Response when enrolling a new MFA method."""

    secret: str
    provisioning_uri: str
    backup_codes: list[str] = Field(default_factory=list)


class TenantConfig(BaseModel):
    """Configuration for provisioning a new tenant."""

    name: str
    admin_email: str
    billing_plan: str = "free"
    idp_type: str = "local"


class IdPConfig(BaseModel):
    """Identity provider federation configuration."""

    type: str
    metadata_url: str = ""
    entity_id: str = ""
    signing_cert: str = ""


__all__ = [
    "AuthenticatedUser",
    "CertificateBundle",
    "DynamicCredential",
    "GroupProfile",
    "IdPConfig",
    "MFASetupResponse",
    "SAMLRequest",
    "SecretMetadata",
    "TenantConfig",
    "TenantContext",
    "UserProfile",
]
