import type { PaletteItem, NodePort } from "@/types";

const INPUT_PORT: NodePort = {
  id: "in",
  label: "Input",
  direction: "input",
  dataType: "any",
  required: true,
};

const OUTPUT_PORT: NodePort = {
  id: "out",
  label: "Output",
  direction: "output",
  dataType: "any",
};

export const PALETTE_ITEMS: PaletteItem[] = [
  // ─── Input / Output ────────────────────────────────────────────────
  {
    type: "inputNode",
    category: "input",
    label: "Input",
    description: "Agent input / entry point",
    icon: "ArrowRightToLine",
    defaultData: {
      label: "Input",
      category: "input",
      description: "Workflow entry point",
      ports: [OUTPUT_PORT],
      config: { inputType: "text", defaultValue: "" },
    },
  },
  {
    type: "webhookTriggerNode",
    category: "input",
    label: "Webhook Trigger",
    description: "Trigger via incoming webhook",
    icon: "Webhook",
    defaultData: {
      label: "Webhook Trigger",
      category: "input",
      description: "HTTP webhook trigger",
      ports: [OUTPUT_PORT],
      config: { method: "POST", path: "/webhook" },
    },
  },
  {
    type: "scheduleTriggerNode",
    category: "input",
    label: "Schedule Trigger",
    description: "Trigger on a cron schedule",
    icon: "Clock",
    defaultData: {
      label: "Schedule Trigger",
      category: "input",
      description: "Cron-based trigger",
      ports: [OUTPUT_PORT],
      config: { cron: "0 * * * *", timezone: "UTC" },
    },
  },
  {
    type: "outputNode",
    category: "output",
    label: "Output",
    description: "Agent output / exit point",
    icon: "ArrowLeftFromLine",
    defaultData: {
      label: "Output",
      category: "output",
      description: "Workflow exit point",
      ports: [INPUT_PORT],
      config: { outputFormat: "text" },
    },
  },
  {
    type: "streamOutputNode",
    category: "output",
    label: "Stream Output",
    description: "Streaming output (SSE / WebSocket)",
    icon: "Radio",
    defaultData: {
      label: "Stream Output",
      category: "output",
      description: "Streaming output",
      ports: [INPUT_PORT],
      config: { format: "sse", chunkSize: 256 },
    },
  },

  // ─── LLM ───────────────────────────────────────────────────────────
  {
    type: "llmNode",
    category: "llm",
    label: "LLM",
    description: "Large Language Model call (OpenAI, Anthropic, etc.)",
    icon: "Brain",
    defaultData: {
      label: "LLM",
      category: "llm",
      description: "Language model call",
      ports: [INPUT_PORT, OUTPUT_PORT],
      config: { model: "gpt-4o", temperature: 0.7, maxTokens: 2048, systemPrompt: "" },
    },
  },
  {
    type: "embeddingNode",
    category: "llm",
    label: "Embedding",
    description: "Generate vector embeddings",
    icon: "Hash",
    defaultData: {
      label: "Embedding",
      category: "llm",
      description: "Embedding generation",
      ports: [INPUT_PORT, OUTPUT_PORT],
      config: { model: "text-embedding-3-small", dimensions: 1536 },
    },
  },
  {
    type: "visionNode",
    category: "llm",
    label: "Vision",
    description: "Vision / multimodal model",
    icon: "Eye",
    defaultData: {
      label: "Vision",
      category: "llm",
      description: "Multimodal vision model",
      ports: [INPUT_PORT, OUTPUT_PORT],
      config: { model: "gpt-4o", maxTokens: 2048, detail: "auto" },
    },
  },
  {
    type: "structuredOutputNode",
    category: "llm",
    label: "Structured Output",
    description: "JSON mode / structured output",
    icon: "Braces",
    defaultData: {
      label: "Structured Output",
      category: "llm",
      description: "JSON-mode structured output",
      ports: [INPUT_PORT, OUTPUT_PORT],
      config: { model: "gpt-4o", schema: "{}", temperature: 0.2 },
    },
  },

  // ─── Tools ─────────────────────────────────────────────────────────
  {
    type: "toolNode",
    category: "tool",
    label: "Tool",
    description: "External tool or API call",
    icon: "Wrench",
    defaultData: {
      label: "Tool",
      category: "tool",
      description: "External tool invocation",
      ports: [INPUT_PORT, OUTPUT_PORT],
      config: { toolName: "", parameters: {} },
    },
  },
  {
    type: "mcpToolNode",
    category: "tool",
    label: "MCP Tool",
    description: "Model Context Protocol tool call",
    icon: "Plug",
    defaultData: {
      label: "MCP Tool",
      category: "tool",
      description: "MCP server tool call",
      ports: [INPUT_PORT, OUTPUT_PORT],
      config: { serverName: "", toolName: "" },
    },
  },
  {
    type: "httpRequestNode",
    category: "tool",
    label: "HTTP Request",
    description: "HTTP / REST API call",
    icon: "Globe",
    defaultData: {
      label: "HTTP Request",
      category: "tool",
      description: "HTTP request",
      ports: [INPUT_PORT, OUTPUT_PORT],
      config: { method: "GET", url: "", headers: "{}", body: "" },
    },
  },
  {
    type: "databaseQueryNode",
    category: "tool",
    label: "Database Query",
    description: "Execute a database query",
    icon: "Database",
    defaultData: {
      label: "Database Query",
      category: "tool",
      description: "Database query",
      ports: [INPUT_PORT, OUTPUT_PORT],
      config: { connectionString: "", query: "", dbType: "postgresql" },
    },
  },
  {
    type: "functionCallNode",
    category: "tool",
    label: "Function",
    description: "Custom function / code execution",
    icon: "Code",
    defaultData: {
      label: "Function",
      category: "tool",
      description: "Custom function execution",
      ports: [INPUT_PORT, OUTPUT_PORT],
      config: { functionName: "", code: "" },
    },
  },

  // ─── Logic ─────────────────────────────────────────────────────────
  {
    type: "conditionNode",
    category: "condition",
    label: "Condition",
    description: "Branch based on a condition",
    icon: "GitBranch",
    defaultData: {
      label: "Condition",
      category: "condition",
      description: "Conditional branching",
      ports: [
        INPUT_PORT,
        { id: "true", label: "True", direction: "output", dataType: "any" },
        { id: "false", label: "False", direction: "output", dataType: "any" },
      ],
      config: { expression: "" },
    },
  },
  {
    type: "switchNode",
    category: "condition",
    label: "Switch",
    description: "Multi-branch switch statement",
    icon: "ListTree",
    defaultData: {
      label: "Switch",
      category: "condition",
      description: "Multi-branch switch",
      ports: [
        INPUT_PORT,
        { id: "case_0", label: "Case 0", direction: "output", dataType: "any" },
        { id: "case_1", label: "Case 1", direction: "output", dataType: "any" },
        { id: "default", label: "Default", direction: "output", dataType: "any" },
      ],
      config: { expression: "", cases: "case_0,case_1" },
    },
  },
  {
    type: "loopNode",
    category: "condition",
    label: "Loop",
    description: "Iterate over items or repeat",
    icon: "Repeat",
    defaultData: {
      label: "Loop",
      category: "condition",
      description: "Iteration loop",
      ports: [
        INPUT_PORT,
        { id: "body", label: "Loop Body", direction: "output", dataType: "any" },
        { id: "done", label: "Done", direction: "output", dataType: "any" },
      ],
      config: { loopType: "forEach", maxIterations: 100 },
    },
  },
  {
    type: "parallelNode",
    category: "condition",
    label: "Parallel",
    description: "Execute branches in parallel",
    icon: "GitFork",
    defaultData: {
      label: "Parallel",
      category: "condition",
      description: "Parallel execution",
      ports: [
        INPUT_PORT,
        { id: "branch_0", label: "Branch 0", direction: "output", dataType: "any" },
        { id: "branch_1", label: "Branch 1", direction: "output", dataType: "any" },
      ],
      config: { branches: 2 },
    },
  },
  {
    type: "mergeNode",
    category: "condition",
    label: "Merge",
    description: "Merge parallel branches",
    icon: "Merge",
    defaultData: {
      label: "Merge",
      category: "condition",
      description: "Merge parallel results",
      ports: [
        { id: "in_0", label: "Input 0", direction: "input", dataType: "any", required: true },
        { id: "in_1", label: "Input 1", direction: "input", dataType: "any", required: true },
        OUTPUT_PORT,
      ],
      config: { strategy: "waitAll" },
    },
  },
  {
    type: "delayNode",
    category: "condition",
    label: "Delay",
    description: "Wait / delay execution",
    icon: "Timer",
    defaultData: {
      label: "Delay",
      category: "condition",
      description: "Delay node",
      ports: [INPUT_PORT, OUTPUT_PORT],
      config: { delayMs: 1000 },
    },
  },

  // ─── RAG ───────────────────────────────────────────────────────────
  {
    type: "vectorSearchNode",
    category: "rag",
    label: "Vector Search",
    description: "Vector similarity search",
    icon: "Search",
    defaultData: {
      label: "Vector Search",
      category: "rag",
      description: "Vector similarity search",
      ports: [INPUT_PORT, OUTPUT_PORT],
      config: { collection: "", topK: 5, threshold: 0.7 },
    },
  },
  {
    type: "documentLoaderNode",
    category: "rag",
    label: "Document Loader",
    description: "Load and chunk documents",
    icon: "FileText",
    defaultData: {
      label: "Document Loader",
      category: "rag",
      description: "Load documents",
      ports: [INPUT_PORT, OUTPUT_PORT],
      config: { source: "", chunkSize: 512, overlap: 64 },
    },
  },

  // ─── Human-in-the-Loop ─────────────────────────────────────────────
  {
    type: "humanApprovalNode",
    category: "human",
    label: "Human Approval",
    description: "Require human approval to proceed",
    icon: "UserCheck",
    defaultData: {
      label: "Human Approval",
      category: "human",
      description: "Human-in-the-loop approval",
      ports: [
        INPUT_PORT,
        { id: "approved", label: "Approved", direction: "output", dataType: "any" },
        { id: "rejected", label: "Rejected", direction: "output", dataType: "any" },
      ],
      config: { approver: "", timeoutMinutes: 60, message: "" },
    },
  },
  {
    type: "humanInputNode",
    category: "human",
    label: "Human Input",
    description: "Request input from a human",
    icon: "MessageSquare",
    defaultData: {
      label: "Human Input",
      category: "human",
      description: "Request human input",
      ports: [INPUT_PORT, OUTPUT_PORT],
      config: { prompt: "", inputType: "text" },
    },
  },

  // ─── Security ──────────────────────────────────────────────────────
  {
    type: "dlpScanNode",
    category: "security",
    label: "DLP Scan",
    description: "Scan for sensitive data (PII, secrets)",
    icon: "ShieldCheck",
    defaultData: {
      label: "DLP Scan",
      category: "security",
      description: "Data loss prevention scan",
      ports: [INPUT_PORT, OUTPUT_PORT],
      config: { policyId: "", action: "redact" },
    },
  },
  {
    type: "costGateNode",
    category: "security",
    label: "Cost Gate",
    description: "Block if cost exceeds threshold",
    icon: "DollarSign",
    defaultData: {
      label: "Cost Gate",
      category: "security",
      description: "Cost threshold gate",
      ports: [
        INPUT_PORT,
        { id: "pass", label: "Pass", direction: "output", dataType: "any" },
        { id: "block", label: "Blocked", direction: "output", dataType: "any" },
      ],
      config: { maxCost: 10, currency: "$" },
    },
  },

  // ─── Sub-agents ────────────────────────────────────────────────────
  {
    type: "subAgentNode",
    category: "subagent",
    label: "Sub-Agent",
    description: "Invoke another agent",
    icon: "Bot",
    defaultData: {
      label: "Sub-Agent",
      category: "subagent",
      description: "Call another agent",
      ports: [INPUT_PORT, OUTPUT_PORT],
      config: { agentId: "", agentName: "" },
    },
  },
];
